services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        - AGENT_VNCPW=${AGENT_VNCPW}
    environment:
      TZ: ${TIMEZONE}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    container_name: openai-agent-python
    ports:
      - "5901:5901"
    tty: true
    stdin_open: true
    restart: always
